version: '3.4'

services:
  sqlserver:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "Prefeitura@123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    mem_limit: 2g
    volumes:
      - sqlserver_data:/var/opt/mssql

volumes:
  sqlserver_data:
